analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    unnecessary_this: ignore
    unnecessary_new: ignore
    unnecessary_cast: ignore
    non_constant_identifier_names: ignore
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    invalid_assignment: ignore
    always_declare_return_types: ignore
    always_use_package_imports: ignore
    avoid_print: ignore
    null_check_on_nullable_type_parameter: ignore
    missing_return: ignore
    invalid_use_of_protected_member: ignore
    invalid_use_of_visible_for_testing_member: ignore
